# JDE credentials / connection
po.statusCodeNext=230
po.p43081Version=ZJDE0002
po.orderTypeCode=OP
po.businessUnitCode=          30
po.statusCodeNext=230
po.statusApproval=2N
po.szCompany=00000
po.szCurrencyCodeTo=USD